name: Update Football Predictions

on:
  schedule:
    # Run every Thursday at 12 PM UTC
    - cron: '0 12 * * 4'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-predictions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run prediction update script
      env:
        API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
      run: |
        python 06_update_predictions.py
        
    - name: Check if predictions were updated
      id: check-changes
      run: |
        if [ -f "docs/predictions.json" ]; then
          echo "Predictions file exists"
          echo "::set-output name=has-predictions::true"
        else
          echo "No predictions file found"
          echo "::set-output name=has-predictions::false"
        fi
        
    - name: Commit and push if changes exist
      if: steps.check-changes.outputs.has-predictions == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/predictions.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update football predictions [skip ci]"
        git push
        
    - name: Comment on commit
      if: steps.check-changes.outputs.has-predictions == 'true'
      run: |
        echo "Predictions updated successfully at $(date)"
        
    - name: Handle failure
      if: failure()
      run: |
        echo "Failed to update predictions"
        exit 1


